### ISSUE TITLE
Check if usage of split fails in Unicode

### ISSUE THREAD

**Issue by Sebmaster** [Sebmaster/tr46.js#1]
Currently `split` is used to break apart the labels of the domain, however split might break apart at the wrong positions if a dot is position right after a surrogate character(?) maybe/probably.

**Comment by TimothyGu** [comment]
The only case where it may breaks is when the dot is between a leading and a trailing surrogate, which is an invalid state anyway. Hence I don't think this is an actual issue.

**Comment by Sebmaster** [comment]
Checked this recently. Not an issue. 👍
