### ISSUE TITLE
Use ES5 instead of ES6 for target

### ISSUE THREAD

**Issue by binarykitchen** [Sebmaster/tr46.js#18]
Including your npm package in other projects without babelification can break.

For example `function findStatus(val, { useSTD3ASCIIRules }) {` breaks on IE11.

See https://stackoverflow.com/questions/29738381/how-to-publish-a-module-written-in-es6-to-npm

**Comment by TimothyGu** [comment]
We do not support old browsers or even old Node.js runtimes:

https://github.com/Sebmaster/tr46.js/blob/8b4b13895dec235dde3a7aaf76572ffee70b3332/package.json#L4-L6

**Comment by gfx** [comment]
@TimothyGu Can you add it to README.md? I have fatal errors on IE11 (via `whatwg-url`) and I have to get it of this module.
